### ISSUE TITLE
NoCaptchaAi v3.5 does not work with Firefox using Violentmonkey

### ISSUE THREAD

**Issue by BoscoFZ** [noCaptchaAi/hCaptchaSolverApi#135]
NoCaptchaAi v3.5 does not work with Firefox using Violentmonkey

P/s
NoCaptchaAi v3.5 work OK with Firefox using Tampermonkey or Chrome using Violentmonkey

**Comment by 404b** [comment]
next update coming soon

**Comment by 404b** [comment]
> NoCaptchaAi v3.5 does not work with Firefox using Violentmonkey
> 
> P/s NoCaptchaAi v3.5 work OK with Firefox using Tampermonkey or Chrome using Violentmonkey

Is this still the case?

**Comment by nocaptchaai-com** [comment]
Tested on Firefox version 110 with UserScript version 3.6.9, working fine.
Please open a new issue with more details if you have issue.
