### ISSUE TITLE
Solve in background w/o focus

### ISSUE THREAD

**Issue by TristanIvanov** [noCaptchaAi/hCaptchaSolverApi#152]
Is there any possibility to solve captchas in the background, without focus of the tab/window?

**Comment by 404b** [comment]
> Is there any possibility to solve captchas in the background, without focus of the tab/window?

try https://github.com/noCaptchaAi/hCaptchaSolver.user.js

or https://github.com/noCaptchaAi/noCaptcha_extension

or https://github.com/noCaptchaAi/nocaptchaai-puppeteer

**Comment by 404b** [comment]
@TristanIvanov Can you try the extension for this?
In my knowledge it does'n not always work but let me know if you have tested extension.
