### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by Pocker88** [noCaptchaAi/hCaptchaSolverApi#154]
Can you help, at this moment ReCaptcha solver beta ver., didn't work? Its the end? Coz for me any ReCaptcha's didnt solve.. thanks for your work!

**Comment by nocaptchaai-com** [comment]
reCAPTCHA not working at the movement. Keeping it active till we make reCAPTCHA live.

**Comment by Pocker88** [comment]
Still nothing Sir?!?

**Comment by 404b** [comment]
> Still nothing Sir?!?

https://github.com/noCaptchaAi/chrome-extension

reCaptcha working version updated. use v1.7.6
