### ISSUE TITLE
Exempley Playwright (python) API

### ISSUE THREAD

**Issue by mkbdes** [noCaptchaAi/hCaptchaSolverApi#28]
hello first I would like to congratulate the project is excellent fulfills more than promised.
but I face difficulties when using with playwright could you show an 
example of how to use "hCaptchaSolverApi" together with playwright.

**Comment by shimuldn** [comment]
I will write an example soon.

**Comment by debpalash** [comment]
> hello first I would like to congratulate the project is excellent fulfills more than promised. but I face difficulties when using with playwright could you show an example of how to use "hCaptchaSolverApi" together with playwright.

There are already sample files for puppeteer and selenium
